export enum PERMS {
    TOURS_MANAGEMENT             = 'tours_management',
    ALL_PROPERTY_MANAGEMENT      = 'all_property_management',
    AMENITY_MANAGEMENT           = 'amenity_management',
    MANAGE_PARTNER               = 'manage_partner',
    SERVICE_MANAGEMENT           = 'service_management',
    FILTER_COPY_ADDRESS          = 'filter_copy_address',
    MOMENT_MANAGEMENT            = 'moment_management',
    HASHTAGS_MANAGEMENT          = 'hashtags_management',
    USER_LIST                    = 'user_list',
    MANAGE_BLANK_PAGE            = 'manage_blank_page',
    REVIEW_IMPORT_MANAGEMENT     = 'review_import_management',
    PROVINCE_MANAGEMENT          = 'province_management',
    PRIVACY_MANAGEMENT           = 'privacy_management',
    MODULE_LIST                  = 'module_list',
    CATEGORY_MANAGEMENT          = 'category_management',
    ADDITIONAL_SERVICE_MANAGEMENT= 'additional_service_management',
    MANAGE_CRUD_BLANK            = 'manage_crud_blank',
    DASHBOARD_SYSTEM             = 'dashboard_system',
    ASSIGNED_USER                = 'assigned_user',
    ROLE_LIST                    = 'role_list',
    ACTIVITY_MANAGEMENT          = 'activity_management',
    PROMOTION_AND_EVENT_MANAGEMENT = 'promotion_and_event_management',
    MANAGE_EMPLOYEE              = 'manage_employee',
    KEYWORD_MANAGEMENT           = 'keyword_management',
    TYPE_MANAGEMENT              = 'type_management',
    HOME_PAGE_MANAGEMENT         = 'home_page_management',
    FEATURE_MANAGEMENT           = 'feature_management',
    APP_USER_MANAGEMENT          = 'app_user_management',
    FOLLOW_UP_MANAGEMENT         = 'follow_up_management',
    SUB_CATEGORY_MANAGEMENT      = 'sub_category_management',
    REQUEST_LIST_PLACE           = 'request_list_place',
  }
  