import { Avatar, Button, Popconfirm, Table, Tooltip } from 'antd'
import { useContext, useEffect, useState } from 'react'
import { AuthContext } from '../../../../contexts/AuthContext'
import { useNavigate } from 'react-router-dom'
import {
  DeleteOutlined,
  EditOutlined,
  EyeOutlined,
  FileImageOutlined,
} from '@ant-design/icons'
//
import SearchDetail from './Search'
import renderActions from 'components/Icon/MoreOption'

const PromotionAndEvent = (props) => {
  const { isConfirmDelete } = props
  const { access_token } = useContext(AuthContext)
  const navigate = useNavigate()
  const [userList, setUserList] = useState([])
  const [currentPage, setCurrentPage] = useState(1)
  const [loading, setLoading] = useState(true)
  const [pageSize, setPageSize] = useState(10)

  // Function to generate a random 10-digit phone number starting with '071'
  const generatePhoneNumber = () => {
    let phone = '071'
    // We need 7 more digits to have a total of 10 digits.
    for (let i = 0; i < 7; i++) {
      phone += Math.floor(Math.random() * 10)
    }
    return phone
  }

  const generateUserData = () => {
    const generatedData = []
    // Sample arrays for randomized data
    const categories = ['Category 1', 'Category 2', 'Category 3']
    const provinces = ['Province A', 'Province B', 'Province C']
    const owners = ['Owner 1', 'Owner 2', 'Owner 3']
    const types = ['Type A', 'Type B', 'Type C']
    const statuses = ['Active', 'Inactive', 'Expired']

    for (let i = 1; i <= 10; i++) {
      // Generate random start and expired dates
      const startDate = new Date(
        Date.now() - Math.floor(Math.random() * 10000000000)
      )
      const expiredDate = new Date(
        startDate.getTime() + Math.floor(Math.random() * 10000000000)
      )

      generatedData.push({
        key: `place_${i}`,
        // For the "Image" column the Avatar uses an icon so we use `name` for reference.
        name: `Place ${i}`,

        // Promotion Name field (sample text)
        promotion_name: `Promotion ${i}`,

        // Location Name field
        location_name: `Location ${i}`,

        // Province field: random selection
        province: provinces[Math.floor(Math.random() * provinces.length)],

        // Start Date: formatted as a locale date string
        start_date: startDate.toLocaleDateString(),

        // Expired Date: formatted as a locale date string
        expired_date: expiredDate.toLocaleDateString(),

        // Type field: random selection
        type: types[Math.floor(Math.random() * types.length)],

        // Status field: random selection
        status: statuses[Math.floor(Math.random() * statuses.length)],

        // Created By field
        create_by: `User ${i}`,

        // Created At: using a random date generated by subtracting random milliseconds from now.
        created_at: new Date(
          Date.now() - Math.floor(Math.random() * 10000000000)
        ).toLocaleDateString(),

        // Additional field for description
        description: `Description for Place ${i}`,
        // If you need phone in the data for any reason, you can add it here:
        phone: generatePhoneNumber(),
      })
    }
    setUserList(generatedData)
    setLoading(false)
  }

  useEffect(() => {
    generateUserData()
  }, [])

  const handleView = (record) => {
    navigate('/category/detail')
  }

  // Add a handleEdit function (not provided earlier)
  const handleEdit = (record) => {
    console.log(`Edit record: ${record.key}`)
    // Implement edit functionality as needed
  }

  const handleDelete = (record) => {
    console.log(`Delete record: ${record.key}`)
  }

  const renderNo = (_, __, index) => {
    return (currentPage - 1) * pageSize + index + 1
  }

  const columns = [
    {
      title: 'No',
      dataIndex: 'no',
      key: 'no',
      width: 50,
      align: 'center',
      render: renderNo,
    },
    {
      title: 'Image',
      dataIndex: 'name',
      key: 'name',
      width: 50,
      align: 'center',
      render: () => (
        <Tooltip title='Click to view image' trigger='click'>
          <Avatar
            shape='square'
            size={24}
            icon={<FileImageOutlined />}
            style={{ cursor: 'pointer' }}
          />
        </Tooltip>
      ),
    },
    {
      title: 'Promotion Name',
      dataIndex: 'promotion_name',
      key: 'promotion_name',
      align: 'center',
    },
    {
      title: 'Location Name',
      dataIndex: 'location_name',
      key: 'location_name',
      align: 'center',
    },
    {
      title: 'Province',
      dataIndex: 'province',
      key: 'province',
      align: 'center',
    },
    {
      title: 'Start Date',
      dataIndex: 'start_date',
      key: 'start_date',
      align: 'center',
    },
    {
      title: 'Expired Date',
      dataIndex: 'expired_date',
      key: 'expired_date',
      align: 'center',
    },
    {
      title: 'Type',
      dataIndex: 'type',
      key: 'type',
      align: 'center',
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      align: 'center',
    },
    {
      title: 'Created By',
      dataIndex: 'create_by',
      key: 'create_by',
      align: 'center',
    },
    {
      title: 'Created At',
      dataIndex: 'created_at',
      key: 'created_at',
      align: 'center',
    },
    {
      title: 'Action',
      dataIndex: 'action',
      key: 'action',
      align: 'center',
      hidden: isConfirmDelete,
      width: 50,
      render: (_, record) => (
        <div className='flex justify-center'>
          <Tooltip title='View'>
            <Button
              icon={<EyeOutlined style={{ color: 'green' }} />}
              shape='circle'
              size='small'
              onClick={() => handleView(record)}
              style={{ marginRight: 8 }}
            />
          </Tooltip>
          <Tooltip title='Edit'>
            <Button
              icon={<EditOutlined />}
              shape='circle'
              size='small'
              onClick={() => handleEdit(record)}
              style={{ marginRight: 8 }}
            />
          </Tooltip>
          <Tooltip title='Delete'>
            <Popconfirm
              title='Are you sure you want to delete this record?'
              // onConfirm={() => ConfirmDelete(record)}
              okText='Yes'
              cancelText='No'
              placement='top'
            >
              <Button
                icon={<DeleteOutlined />}
                shape='circle'
                size='small'
                danger
              />
            </Popconfirm>
          </Tooltip>
        </div>
      ),
    },
  ]

  const pagination = {
    current: currentPage,
    pageSize: pageSize,
    total: userList?.length,
    onChange: (page, pageSize) => {
      setCurrentPage(page)
      setPageSize(pageSize)
    },
    showSizeChanger: true,
    pageSizeOptions: ['10', '20', '50', '100'],
  }
  return (
    <>
      <Table
        columns={columns}
        dataSource={userList}
        pagination={pagination}
        bordered={false}
        size='small'
        loading={loading}
        scroll={{ x: 'max-content' }}
        className='custom-table-category'
        rowClassName={(record, index) =>
          index % 2 === 0 ? 'even-row' : 'odd-row'
        }
      />
    </>
  )
}

export default PromotionAndEvent
